# backend/reports/pdf_generator.py

import os
from datetime import datetime
from sqlalchemy import text
from fpdf import FPDF
from db.database import get_engine

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "reports")


class CreditLensPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(15, 32, 65)
        self.set_text_color(255, 255, 255)
        self.rect(0, 0, 210, 22, "F")
        self.set_xy(0, 5)
        self.cell(0, 12, "CreditLens  —  Monthly Risk Report", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(18)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by CreditLens Analytics", align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 12)
        self.set_fill_color(230, 236, 245)
        self.set_text_color(15, 32, 65)
        self.cell(0, 9, f"  {title}", ln=True, fill=True)
        self.set_text_color(0, 0, 0)
        self.ln(3)

    def kpi_row(self, label, value, highlight=False):
        self.set_font("Helvetica", "", 11)
        if highlight:
            self.set_fill_color(255, 243, 220)
            fill = True
        else:
            self.set_fill_color(250, 250, 250)
            fill = True
        self.cell(110, 8, f"  {label}", border="B", fill=fill)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, str(value), border="B", ln=True, fill=fill)
        self.set_font("Helvetica", "", 11)
        self.ln(1)

    def segment_table(self, rows):
        self.set_font("Helvetica", "B", 10)
        self.set_fill_color(15, 32, 65)
        self.set_text_color(255, 255, 255)
        self.cell(130, 8, "  Segment Label", border=1, fill=True)
        self.cell(0, 8, "  Customer Count", border=1, ln=True, fill=True)
        self.set_text_color(0, 0, 0)

        for i, (label, count) in enumerate(rows):
            self.set_font("Helvetica", "", 10)
            if i % 2 == 0:
                self.set_fill_color(245, 248, 252)
            else:
                self.set_fill_color(255, 255, 255)
            self.cell(130, 7, f"  {label}", border=1, fill=True)
            self.cell(0, 7, f"  {count}", border=1, ln=True, fill=True)
        self.ln(4)


def fetch_stats(engine):
    with engine.connect() as conn:
        row = conn.execute(text("""
            SELECT
                COUNT(*)                                                AS total_customers,
                SUM(CASE WHEN churn_risk_score > 0.7 THEN 1 ELSE 0 END) AS high_risk_count,
                ROUND(AVG(churn_risk_score)::numeric, 4)               AS avg_churn_score,
                SUM(CASE WHEN is_churned THEN 1 ELSE 0 END)            AS churned_count
            FROM customers
        """)).fetchone()

        total_customers = int(row[0]) if row[0] else 0
        high_risk_count = int(row[1]) if row[1] else 0
        avg_churn_score = float(row[2]) if row[2] else 0.0
        churned_count   = int(row[3]) if row[3] else 0

        seg_rows = conn.execute(text("""
            SELECT segment_label, COUNT(*) AS cnt
            FROM customers
            WHERE segment_label IS NOT NULL
            GROUP BY segment_label
            ORDER BY cnt DESC
        """)).fetchall()
        segments = [(r[0], int(r[1])) for r in seg_rows]

        fraud_row = conn.execute(text("""
            SELECT COUNT(*) FROM transactions WHERE fraud_flag = TRUE
        """)).fetchone()
        fraud_count = int(fraud_row[0]) if fraud_row[0] else 0

    return {
        "total_customers": total_customers,
        "high_risk_count": high_risk_count,
        "avg_churn_score": avg_churn_score,
        "churned_count":   churned_count,
        "segments":        segments,
        "fraud_count":     fraud_count,
    }


def generate_report(report_month: str = None) -> str:
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    if report_month is None:
        report_month = datetime.now().strftime("%Y_%m")

    engine = get_engine()
    stats  = fetch_stats(engine)

    pdf = CreditLensPDF()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 7, f"Report Period: {report_month.replace('_', ' ')}   |   "
                   f"Generated: {datetime.now().strftime('%d %b %Y, %H:%M UTC')}", ln=True)
    pdf.ln(4)

    pdf.section_title("Key Performance Indicators")
    high_risk_pct = (
        round(stats["high_risk_count"] / stats["total_customers"] * 100, 2)
        if stats["total_customers"] > 0 else 0.0
    )
    pdf.kpi_row("Total Customers",            f"{stats['total_customers']:,}")
    pdf.kpi_row("Churned Customers (actual)", f"{stats['churned_count']:,}")
    pdf.kpi_row("High-Risk Customers (score > 0.7)",
                f"{stats['high_risk_count']:,}  ({high_risk_pct}%)", highlight=True)
    pdf.kpi_row("Average Churn Risk Score",   f"{stats['avg_churn_score']:.4f}")
    pdf.kpi_row("Flagged Fraud Transactions", f"{stats['fraud_count']:,}", highlight=True)
    pdf.ln(4)

    pdf.section_title("Customer Segment Breakdown")
    if stats["segments"]:
        pdf.segment_table(stats["segments"])
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, "  No segment data available.", ln=True)
        pdf.ln(2)

    pdf.section_title("Risk Distribution Commentary")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(50, 50, 50)
    commentary = (
        f"As of {report_month.replace('_', '/')}, CreditLens has profiled "
        f"{stats['total_customers']:,} customers. "
        f"Of these, {stats['high_risk_count']:,} ({high_risk_pct}%) are classified as "
        f"high churn risk with a score exceeding 0.70. "
        f"The portfolio-wide average churn risk score stands at {stats['avg_churn_score']:.4f}. "
        f"The fraud detection module flagged {stats['fraud_count']:,} transactions as anomalous. "
        f"Retention campaigns should prioritize high-risk segments identified above."
    )
    pdf.multi_cell(0, 6, commentary)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    pdf.section_title("Model & Data Notes")
    pdf.set_font("Helvetica", "", 9)
    notes = [
        "Churn Risk Score: XGBoost classifier trained on BankChurners dataset.",
        "Segmentation: K-Means (k=5) on credit/transaction/risk features.",
        "Fraud Detection: Isolation Forest on creditcard.csv (V1-V4, Amount).",
        "High-risk threshold: churn_risk_score > 0.70.",
    ]
    for note in notes:
        pdf.cell(6, 6, chr(149), ln=False)
        pdf.cell(0, 6, note, ln=True)

    filename = f"creditlens_report_{report_month}.pdf"
    filepath = os.path.join(OUTPUT_DIR, filename)
    pdf.output(filepath)
    print(f"[Report] Saved: {filepath}")
    return filename


if __name__ == "__main__":
    fname = generate_report()
    print(f"Generated: {fname}")